game.create:
  path: /game
  defaults:
    _controller: AppBundle:Game:create
  methods:
    - POST

game.player.read:
  path: /game/{player}
  defaults:
    _controller: AppBundle:Game:playerRead
  methods:
    - GET
  requirements:
    - \d+

game.play:
  path: /game/{player}/play
  defaults:
    _controller: AppBundle:Game:play
  methods:
    - POST
  requirements:
    - \d+

game.player.history:
  path: /game/{player}/history
  defaults:
    _controller: AppBundle:Game:history
  methods:
    - GET
  requirements:
    - \d+