AppBundle\Entity\Game:
  type: entity
  table: games
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    playerHand:
      type: string
      length: 32
      nullable: false
    computerHand:
      type: string
      length: 32
      nullable: false
    outcome:
      type: string
      length: 32
      nullable: false
  manyToOne:
    player:
      targetEntity: AppBundle\Entity\Player
      inversedBy: games
      joinColumn:
        name: player_id
        referencedColumnName: id