AppBundle\Entity\Player:
  type: entity
  table: players
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 32
      nullable: false
  oneToMany:
    games:
      targetEntity: AppBundle\Entity\Game
      mappedBy: player